services:
  laptop:
    build:
      context: .
      dockerfile: Dockerfile.Laptop
    container_name: laptop
    networks:
      wifi:
        ipv4_address: 192.168.1.20
    ports:
     - "22:22"
    restart: unless-stopped

  comp-machine:
    build:
      context: .
      dockerfile: Dockerfile.CompMachine
    container_name: comp_machine
    networks:
      wifi:
        ipv4_address: 192.168.1.10
    restart: unless-stopped

  battlestation:
    image: vulhub/webmin:1.910
    container_name: battlestation
    networks:
      wifi:
        ipv4_address: 192.168.1.74
    volumes:
        - type: bind
          source: ./Battlestation/SECRET_doNotOpen_onPainOfDeath.txt
          target: /usr/share/webmin/SECRET_doNotOpen_onPainOfDeath.txt
    restart: unless-stopped

  apache-php:
    build:
      context: .
      dockerfile: Dockerfile.c2c
    container_name: c2c_server
    ports:
      - "80:80"
    restart: unless-stopped

networks:
  wifi:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24